### PR TITLE
updated your portfolio

### LINKED ISSUE #2: Addition of Landing Page Blocks for Semester 7 Repo on College Assignment Page
Please Integrate a separate block for Sem 7 Repo similar to that of other semester repos in Assignments Section.

### PR DESCRIPTION
**Pull request by chaudharishreyas**
I uploaded new images and link SEM 7 (SPPU) labs program on your portfolio.

### CODE REVIEW

**Comment by sudesh-p** [comment]
Good Work!! Though I cant review it right now as I'm short of Coffee. Will Review the Code Tommorow and merge/revert your PR.

**Comment by chaudharishreyas** [comment]
Its on you sir when where you want merged
Thank you,
Shreyas

**Comment by sudesh-p** [comment]
Great Work @chaudharishreyas ..

**Comment by chaudharishreyas** [comment]
Thank you sir..!!

**Pull request merged**
